# HOWTO add a new implementation (named "foo"):
# - Add "foo" to the IMPLS variable (alphabetical order)
# - Add a new "foo_STEP_TO_PROG" variable.
# - Add an "impls/foo/run" script.
# - Add an "impls/foo/Makefile"
# - Add an "impls/foo/Dockerfile"
# - Implement each step in "impls/foo/".

#
# Implementation specific settings
#
IMPLS = js

#
# Implementation specific utility functions
#
js_STEP_TO_PROG = $($(1)).mjs
